### PR TITLE
alternative working download URL for PT-sans

### PR DESCRIPTION
**Pull request by hholzgra**
fontstock.com seems to have changed into some stock trading spam site

### CODE REVIEW

**Comment by hholzgra** [comment]
fontstock.com seems to have changed into some stock trading spam site, changed download address to working fontsquirrel URL

**Comment by Zverik** [comment]
Thanks a lot, Hartmut!

**Comment by hholzgra** [comment]
By the way: I added Velomap as a style choice for my MapOSMatic instance on https://maposmatic.osm-baustelle.de/

See also https://blog.osm-baustelle.de/index.php/2017/07/03/veloroad-ru-style/

**Comment by Zverik** [comment]
I follow your blog since I wrote about it in shtosm this January, and the latest post was quite a surprise :)

**Pull request merged**
